### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by Ronkleman** [adrWasTaken/CanvasPlus#10] opened 2021-05-09 22:57 UTC
The search bar still won't load for me, even after 0.2.1

**Comment by adrWasTaken** [comment] 2021-05-12 01:58
Most likely the issue is that one of your courses doesn't have modules enabled, and the extension assumes it does. Let me know if this is the case. Either way, I'm working on a fix!

**Comment by kittyconfusion** [comment] 2021-05-12 03:00
I can back up @Ronkleman. I am not sure if the search functionality is universal or by course, but I have been unable to get a working search in any of my courses, even those with the modules tab enabled.

**Comment by adrWasTaken** [comment] 2021-05-12 12:34
If any of your courses have modules disabled, your search will never work. More details here https://github.com/adrWasTaken/CanvasPlus/issues/12

**Comment by adrWasTaken** [comment] 2021-05-19 13:00
Fixed in version 0.2.2

**Closed by adrWasTaken** 2021-05-19 13:00 UTC
