### ISSUE TITLE
Search Bar Not loading

### ISSUE THREAD

**Issue by J-Coding-Dev** [adrWasTaken/CanvasPlus#8] opened 2021-05-07 15:14 UTC
I am currently trying to edit this, so it works as a Firefox addon, I managed to get everything working except the search bar, at first as thought this must be a issue with my edits, but when I tested the extension unedited on chrome I had the same issue. This could just be a issue that only happens for my pc for whatever reason or the extension only works for chromebooks (I am using a 64 bit windows pc with chrome 90.0.4430.93 and firefox 89.0.1). I will probably spend some more time trying to debug the issue and will update this is I find what the issue was or the solution. I was using version 0.2.1, I will probably try older versions to see if that fixes the issue. Thanks!

Edit: I think that I have found the issue, I think the issue is in src/inject/search/search.js on line 22, the issue code is "TypeError: /api/v1/users/self/favorites/courses?include[]=term&exclude[]=enrollment is not a valid URL." I am assuming this is a error with the canvas api.

**Comment by adrWasTaken** [comment] 2021-05-12 01:55
Most likely the issue is that one of your courses doesn't have modules enabled, and the extension assumes it does. Let me know if this is the case.

**Comment by J-Coding-Dev** [comment] 2021-05-12 14:49
Yes this seems to be the issue, I have two courses that did not have modules.

**Comment by adrWasTaken** [comment] 2021-05-19 13:00
Fixed in version 0.2.2

**Closed by adrWasTaken** 2021-05-19 13:00 UTC
